### ISSUE TITLE
Translate *.js files not cited in #1

### ISSUE THREAD

**Issue by Fcmam5** [reactjs/ar.reactjs.org#112]
Some pages & components are not cited in #1, like:

- [x] 404 page (@3imed-jaberi) #179
- [x] Acknowlegements page (@3imed-jaberi ) #181  
- [x] JsxCompiler (@3imed-jaberi ) #178 
- [x] Languages page (@3imed-jaberi ) #185
- [x] Versions page (@3imed-jaberi ) #177 
- [x] AllBlogPosts (@3imed-jaberi ) #182 
- [x] CodepenExample (@3imed-jaberi ) #180
- [x] NavigationFooter (@3imed-jaberi) #184 

---

<div dir="rtl">
أستطيع أن أبدأ في العمل عليها اليوم بعد اذنكم :smile: 
</div>

**Comment by mohshbool** [comment]
@Fcmam5 if you want some help, just let me know brother 🤝

**Comment by Fcmam5** [comment]
> @Fcmam5 if you want some help, just let me know brother handshake

That would be great, I guess that we should finish the issues in the first (@iRayan7 what do you think?) issue before. Otherwise yes we can jump into it together :smiley: !

**Comment by mohshbool** [comment]
> > @Fcmam5 if you want some help, just let me know brother handshake
> 
> That would be great, I guess that we should finish the issues in the first (@iRayan7 what do you think?) issue before. Otherwise yes we can jump into it together 😃 !

Of course, that would be better imo but I thought you were gonna start working on them so I just wanted to offer help 😅.

**Comment by iRayan7** [comment]
> > @Fcmam5 if you want some help, just let me know brother handshake
> 
> That would be great, I guess that we should finish the issues in the first (@iRayan7 what do you think?) issue before. Otherwise yes we can jump into it together 😃 !

Yes, let us finish the pages on #1 first 👍. Thanks guys!

**Comment by aladin002dz** [comment]
everything looks good, thanks for the great work all the team ✌️
please, for anything wrong update!
