### ISSUE TITLE
Translating community section

### ISSUE THREAD

**Issue by iRayan7** [reactjs/ar.reactjs.org#117]
**Before you start working**
- Check if the page isn't assigned, and no one commented about it.
- Please comment 👇the page name before you start working on it. To get assigned to it. 

Pages:
- [x] Support (@Fcmam5) #113 
- [x] Articles (@3imed-jaberi) #140 
- [x] Conferences (@3imed-jaberi) #146 
- [x] Courses (@moast) #148 
- [x] Examples (@mohshbool) #166 
- [x] External resources (@3imed-jaberi) #142 
- [x] Meetups (@3imed-jaberi) #127 
- [x] nav.yml (@Aissaoui-Ahmed) #144
- [x] Podcasts (~~@maskeddeveloper) #150~~ (@3imed-jaberi) #168 
- [x] tools-comp-workbenches (@3imed-jaberi) #160 
- [x] tools-data-fetching (@3imed-jaberi) #143  
- [x] tools-debugging (@3imed-jaberi) #129 
- [x] tools-jsx (@Aissaoui-Ahmed) #157 
- [x] tools-misc (@Aissaoui-Ahmed) #161 
- [x] tools-model-mgmt (@3imed-jaberi) #164  
- [x] tools-routing (@3imed-jaberi ) #159 
- [x] tools-starter-kits (@AzizAK) #165 
- [x] tools-testing (@3imed-jaberi) #147
- [x] tools-ui-components (@3imed-jaberi ) #174 
- [x] videos (@3imed-jaberi) #156

**Comment by YousefQaisi** [comment]
Articles

**Comment by 3imed-jaberi** [comment]
> Articles

Hey @YousefQaisi ! 
Okay, you can fork, clone create another branch on which you change the title of the the page you booked, and then send the pull request.

Happy working ✌️

**Comment by Aissaoui-Ahmed** [comment]
- [x] nav.yml

**Comment by maskeddeveloper** [comment]
@iRayan7 i'll take Podcasts

**Comment by moast** [comment]
I'll take courses

**Comment by moast** [comment]
@iRayan7  I'll take Courses

**Comment by 3imed-jaberi** [comment]
Welcome @moast , 
Thank you for your interest in Arabic content.
You can start contributing via the attached steps in the [README.md](https://github.com/reactjs/ar.reactjs.org/blob/master/README.md) file.

**Comment by moast** [comment]
@3imed-jaberi I translated Courses page and pushed it https://github.com/moast/ar.reactjs.org :)

**Comment by 3imed-jaberi** [comment]
@moast , thnak you for your contribution ...
Please create a Pull Request. If you don't know how to do this follow this [video](https://www.youtube.com/watch?v=l5NrYIa_aG4) ..

**Comment by 3imed-jaberi** [comment]
@moast , thank you for your contribution ...

You have created your PR. You can follow it via #148

**Comment by moast** [comment]
> @moast , thank you for your contribution ...
> 
> I have created your PR. You can follow it via #148

Thanks!

**Comment by Aissaoui-Ahmed** [comment]
i'll take
- [x] tools-jsx

**Comment by Aissaoui-Ahmed** [comment]
- [x] tools-misc

**Comment by AzizAK** [comment]
Hey guys,

Thanks for the GREAT work. I would like to help with translating (tools-starter-kits).

**Comment by aladin002dz** [comment]
Translating community section is done, all PR reviewed and merged! 
for anything wrong, please update ✌️
